// Generated by Tools/bake_terrain_patterns.py; do not hand-edit.
#define TerrainPatternPeriod 2.0
#define TerrainSandPatternPeriod 8.0
#define TerrainGrassTileMetres 1.4
#define TerrainGrassAmplitudeMetres 0.020
#define TerrainGrassSourceTexels 4096.0
#define TerrainGrassMinimumLod 2.0
#define TerrainSandTileMetres 1.0
#define TerrainSandAmplitudeMetres 0.120
#define TerrainSandSourceTexels 4096.0
#define TerrainSandMinimumLod 2.0
#define TerrainSnowTileMetres 1.0
#define TerrainSnowAmplitudeMetres 0.060
#define TerrainSnowSourceTexels 2048.0
#define TerrainSnowMinimumLod 2.0
