// Generated by Tools/bake_stone_relief.py; do not edit independently.
#define TerrainStoneTileMetres 12.0
#define TerrainStoneAmplitudeMetres 0.500
#define TerrainStoneSourceTexels 4096.0
#define TerrainStoneMinimumLod 1.0
