"""Generate the CPU collision view of the canonical HLSL regular-cell tables."""
from pathlib import Path
import re

root = Path(__file__).resolve().parents[1]
source = root / "Assets/shaders/voxels/transvoxel_regular_tables.hlsl"
target = root / "Code/Voxels/VoxelCollisionTables.cs"
text = source.read_text()
output = ["// Generated by Tools/generate_collision_tables.py; do not hand-edit.",
          "// Canonical data: Assets/shaders/voxels/transvoxel_regular_tables.hlsl.",
          "// Copyright (c) 2009 Eric Lengyel; MIT license in Assets/shaders/voxels/LICENSE-Transvoxel.txt.",
          "internal static class VoxelCollisionTables", "{"]
for name, size, body in re.findall(r"static const uint (\w+)\[(\d+)\]\s*=\s*\{([^}]+)\};", text):
    values = re.findall(r"0x[0-9a-fA-F]+|\b\d+\b", body)
    assert len(values) == int(size), name
    output += [f"\tpublic static readonly int[] {name} =", "\t{"]
    for i in range(0, len(values), 16):
        output.append("\t\t" + ", ".join(values[i:i+16]) + ",")
    output += ["\t};"]
output += ["}", ""]
target.write_bytes("\r\n".join(output).encode())
